//PART OF THE HTML DOVUMNT TO SAVE
//TO CREATE FILE TO SAVE
function saveDynamicDataToFile() {

	var saveText =
`---
layout: bibleNodeGraph-1
title: "` + bibleNodesTitle.innerText + `"
categories: [BibleNodeGraph]
---

    <div id="nodeCanvas">` + nodeCanvas.innerHTML +
	`</div>` +
	`<div id="connectionDetails">` +
	connectionDetails.innerHTML +
	`</div>`;
		////////////////////////////////////////////////////////////////////////////////////////////
		//REMOVE THE MODIFICATION ADDED BY REFTAGGER BEFORE SAVING
		//This is useful for when you make a correction in a Bible reference or else it would still link to the old reference.
		saveText.toString();
		saveText = saveText.replace(/(>(\s|\n)+<)/g, "> <");
		saveText = saveText.replace(/<a[\s]*class="rtBibleRef"[\s]*([^>]*)>((?:(.|\n)(?!\<\/a\>))*(.|\n))<\/a>/g, "$2");
		//remove inline css generated by darkReader chrome plugin
		saveText = saveText.replace(/((((data-)*)|(--))*(darkreader)([^\s*]+)((\s\d*\w*)*)+(;|(?<!;)"))/g, "");
		//remove all inline styles
		// saveText = saveText.replace(/(style=\"[^\"]*\")/g, "");
		saveText = saveText.replace(/(contenteditable="false")/g, "");
		////////////////////////////////////////////////////////////////////////////////////////////

	console.log(saveText);

	var fname = bibleNodesTitle.innerHTML;
	if (fname == "") {
		customAlert("!!! PLEASE <h1>ENTER TITLE</h1> FOR THE STORY LINE !!!");
		return false;
	} else {

		var filename = fname + `.html`;

		var blob = new Blob([saveText], {
			type: "text/plain;charset=utf-8"
		});
		saveAs(blob, filename);
	}
}